import type { StoryNode } from "../types";

/**
 * 第二章「猟場の書付」
 *
 * 七週間後。ホームズは電報でドニソープへ呼び戻される。
 * 老トレヴァーは卒中で倒れ、ハドスンは三日前に姿を消している。
 *
 * 調査ハブ c2_hub で、4地点のうち2地点を選ぶ（6通り）。
 * 各調査は必ず c2_hub へ戻り、2地点を終えると c3_0 へ進む。
 */
export const chapter2Nodes: StoryNode[] = [
  {
    id: "c2_0",
    chapter: "第二章",
    location: "大学の下宿",
    scene: "college",
    characters: ["holmes"],
    text: [
      "七週間後。十月の終わりだった。",
      "夕方、下宿に電報が届いた。差出人はヴィクター・トレヴァー。文面は七語しかなかった。",
      "「タノム スグ ドニソープヘ コイ ヴィクター」",
      "わたしはその夜の汽車に乗った。",
    ],
    addClues: [],
    audio: [
      { kind: "bgm", asset: "unease", volume: 0.35 },
      { kind: "se", asset: "rain", volume: 0.4 },
    ],
    next: "c2_1",
  },
  {
    id: "c2_1",
    chapter: "第二章",
    location: "ドニソープ",
    scene: "manor",
    text: [
      "雨だった。夏に見たときとは別の土地のように見えた。",
      "葦は倒れ、水は鉛の色をして、沼と空の境がどこにもない。駅から屋敷までの一マイルを歩くあいだに、外套の裾は泥で重くなった。",
      "屋敷の窓は、二階の一つだけが明るかった。",
    ],
    audio: [{ kind: "se", asset: "rain", volume: 0.5 }],
    next: "c2_2",
  },
  {
    id: "c2_2",
    chapter: "第二章",
    location: "屋敷の玄関",
    speaker: "ヴィクター",
    scene: "hall",
    characters: ["victor"],
    text: [
      "ヴィクターは玄関で待っていた。七週間で、彼は五つ歳をとったように見えた。",
      "「親父が倒れた。卒中だ。フォーダム先生が、今夜が峠だと」",
      "「いつだ」",
      "「一昨日の夕方。……ホームズ、聞いてくれ。倒れる直前に、親父は一通の手紙を読んだんだ」",
    ],
    audio: [{ kind: "se", asset: "door", volume: 0.5 }],
    next: "c2_3",
  },
  {
    id: "c2_3",
    chapter: "第二章",
    location: "二階の寝室",
    speaker: "フォーダム医師",
    scene: "hall",
    characters: ["fordham", "trevor"],
    text: [
      "二階の寝室で、トレヴァー老人は仰向けに横たわっていた。顔の右半分が下がり、呼吸のたびに喉が鳴る。",
      "枕元の椅子には、村医のフォーダム医師がいた。細い、神経質そうな男で、白い手袋を膝の上でしきりに揉んでいる。",
      "「血の管が切れとります。もう言葉は出ません」医師は立ち上がった。「わたしはこの方を十七年診てきましたが……こうなることは、正直、予想しておりました」",
    ],
    addClues: ["trevor_stroke"],
    audio: [{ kind: "se", asset: "clock", volume: 0.35 }],
    next: "c2_4",
  },
  {
    id: "c2_4",
    chapter: "第二章",
    location: "書斎",
    speaker: "ヴィクター",
    scene: "study",
    characters: ["victor", "holmes"],
    text: [
      "書斎で、ヴィクターは一枚の紙をわたしに渡した。",
      "「これだ。これを読んで、親父は倒れた」",
      "灰色の粗い紙。細かい、几帳面すぎるほどの筆跡。差出人の署名はない。消印はハンプシャー。",
    ],
    audio: [{ kind: "se", asset: "paper", volume: 0.5 }],
    next: "c2_5",
  },
  {
    id: "c2_5",
    chapter: "第二章",
    location: "書斎",
    scene: "study",
    characters: ["holmes"],
    text: [
      "『猟期も半ば、終了まで三週。ハドスンより報せあり。全部で五十羽、白状すれば少ない。至急、追加の逃亡防止網、手配を乞う。』",
      "わたしは三度読んだ。",
      "猟場の管理についての、何の変哲もない業務連絡だった。これを読んで人が倒れる道理がない。",
      "──だが、道理がないということ自体が、この紙のいちばん大きな異常だった。",
    ],
    addClues: ["cipher_note"],
    audio: [{ kind: "bgm", asset: "unease", volume: 0.4 }],
    next: "c2_6",
  },
  {
    id: "c2_6",
    chapter: "第二章",
    location: "書斎",
    speaker: "ホームズ",
    scene: "study",
    characters: ["holmes", "victor"],
    text: [
      "「ヴィクター。ハドスンはどこだ」",
      "「いない。四日前に出ていった。親父と大喧嘩をして……ハンプシャーのビードウズさんのところへ行く、と言い残して」",
      "「ビードウズ」",
      "「親父の古い知り合いだ。年に一度、手紙のやりとりがあるくらいの。会ったことはない」",
      "消印はハンプシャー。ハドスンの行き先もハンプシャー。そして手紙は、ハドスンが着いた翌日に投函されている。",
    ],
    next: "c2_7",
  },
  {
    id: "c2_7",
    chapter: "第二章",
    location: "書斎",
    speaker: "ホームズ",
    scene: "study",
    characters: ["holmes"],
    text: [
      "その夜、わたしは書斎の灯を落とさなかった。",
      "屋敷の主は口をきけず、鍵を握っていた男は消え、残されたのは意味の通らない紙が一枚。",
      "夜が明けるまでに調べられるのは、せいぜい二か所だ。雨は強くなっている。",
    ],
    audio: [{ kind: "se", asset: "rain", volume: 0.45 }],
    next: "c2_hub",
  },

  // ── 調査ハブ ───────────────────────────────
  {
    id: "c2_hub",
    chapter: "第二章",
    location: "屋敷",
    scene: "study",
    characters: ["holmes"],
    text: ["どこから手をつける。"],
    investigationHub: { afterHub: "c3_0" },
  },

  // ── 調査A：書斎の机 ───────────────────────
  {
    id: "inv_desk_0",
    chapter: "第二章",
    location: "書斎",
    scene: "study",
    characters: ["holmes"],
    text: [
      "老人の書き物机は、この部屋でただ一つ、鍵のかかる家具だった。",
      "鍵は老人の寝間着の胸に、紐で吊るされたままだった。ヴィクターは何も言わずにそれを外して、わたしに渡した。",
      "引き出しは三段。上二段には領収書と土地の書類。三段目は空だった。──空すぎた。",
    ],
    audio: [{ kind: "se", asset: "paper", volume: 0.45 }],
    next: "inv_desk_1",
  },
  {
    id: "inv_desk_1",
    chapter: "第二章",
    location: "書斎",
    speaker: "ホームズ",
    scene: "study",
    characters: ["holmes"],
    text: [
      "引き出しを完全に引き抜いて、裏返した。",
      "底板が二重になっている。爪を差し込むと、乾いた音を立てて薄い板が浮いた。",
      "その下に、四つ折りの紙が一枚。一八五五年の日付が入った、ロンドンのある銀行の帳簿の切れ端だった。行員名簿の欄に、細かい署名が並んでいる。",
      "そのうちの一つ。ジェイムズ・アーミテージ。",
    ],
    addClues: ["ledger_name"],
    next: "inv_desk_2",
  },
  {
    id: "inv_desk_2",
    chapter: "第二章",
    location: "書斎",
    scene: "study",
    characters: ["holmes"],
    text: [
      "J・A。肘の内側に残っていた二文字。",
      "机の上の書き損じの束にも、目を通した。請求書の裏、封筒の切れ端。その中に一枚だけ、性質の違う紙が混じっていた。",
      "あの猟場の書付の文面が、三度、書き写してある。しかも一語ごとに、定規で引いたような縦線が入っている。",
      "老人は、この文面を数えていた。",
    ],
    addClues: ["cipher_key"],
    audio: [{ kind: "se", asset: "clock", volume: 0.3 }],
    next: "c2_hub",
  },

  // ── 調査B：屋根裏のハドスンの部屋 ─────────
  {
    id: "inv_attic_0",
    chapter: "第二章",
    location: "屋根裏",
    scene: "attic",
    characters: ["holmes"],
    text: [
      "屋根裏は、雨の音がいちばん近い場所だった。",
      "斜めの天井、剥き出しの梁、鉄の寝台が一つ。ハドスンが四か月暮らした部屋は、四日前に出ていったきり、誰も手をつけていなかった。",
      "煙草と、汗と、獣脂の匂いが残っている。",
    ],
    audio: [{ kind: "se", asset: "rain", volume: 0.55 }],
    next: "inv_attic_1",
  },
  {
    id: "inv_attic_1",
    chapter: "第二章",
    location: "屋根裏",
    scene: "attic",
    characters: ["holmes"],
    text: [
      "寝台の脚に、紐が括りつけてあった。",
      "先が擦り切れて、何度も結び直した跡がある。結び方が特徴的だった。輪を二重に通し、端を折り返して差し込む。片方を引けば一瞬でほどけ、そうでなければ決してゆるまない。",
      "陸の人間はこの結びを使わない。帆船の甲板で、片手で、揺れる船の上で結ぶための結びだ。",
    ],
    addClues: ["sailors_knot"],
    next: "inv_attic_2",
  },
  {
    id: "inv_attic_2",
    chapter: "第二章",
    location: "屋根裏",
    speaker: "ホームズ",
    scene: "attic",
    characters: ["holmes"],
    text: [
      "寝台の下に、帆布の袋が押し込まれていた。",
      "船乗りの荷物袋だ。中には替えの上着、剃刀、櫛、真鍮の煙草入れ。そして底に、油紙に包んだ紙幣の束があった。数えると、この土地の作男が三十年働いても貯まらない額だ。",
      "わたしは袋の口を閉じ、しばらく動けなかった。",
      "「四か月脅し取った金を全部置いて、着替えも持たずに、男は出ていったのか」",
    ],
    addClues: ["hudson_kit"],
    audio: [{ kind: "se", asset: "heartbeat", volume: 0.4 }],
    next: "c2_hub",
  },

  // ── 調査C：村の宿と郵便局 ─────────────────
  {
    id: "inv_village_0",
    chapter: "第二章",
    location: "村",
    scene: "village",
    characters: ["holmes"],
    text: [
      "雨の中を一マイル歩いて、村へ出た。",
      "宿屋が一軒、郵便局が一軒、鍛冶屋が一軒。それがドニソープという村のすべてだった。",
      "宿の帳場で、わたしは主人に葡萄酒をおごり、三十年前の話を聞かせてくれと頼んだ。田舎の宿の主人ほど、記録を捨てない人種はいない。",
    ],
    audio: [
      { kind: "se", asset: "rain", volume: 0.35 },
      { kind: "se", asset: "door", volume: 0.4 },
    ],
    next: "inv_village_1",
  },
  {
    id: "inv_village_1",
    chapter: "第二章",
    location: "村の宿",
    scene: "village",
    characters: ["holmes"],
    text: [
      "帳場の奥から出てきたのは、湿気で頁が貼りついた古新聞の綴じ込みだった。",
      "一八五五年、十一月。海難の記事。",
      "『囚人輸送船グローリア・スコット号、南大西洋北緯十五度二十分・西経二十五度十四分の海域にて火薬庫爆発、沈没。乗員乗客あわせて九十余名、全員行方不明。ただし一名、通りかかりし帆船に救助さる。同船水夫、ハドスン』",
      "わたしは頁を破りたい衝動を、かろうじて抑えた。",
    ],
    addClues: ["news_clip"],
    audio: [{ kind: "se", asset: "paper", volume: 0.5 }],
    next: "inv_village_2",
  },
  {
    id: "inv_village_2",
    chapter: "第二章",
    location: "郵便局",
    scene: "village",
    characters: ["holmes"],
    text: [
      "郵便局は閉まっていたが、軒下の掲示板は誰でも読める。",
      "船の出入りのある土地だから、潮見表が貼ってある。この沼と海をつなぐ水路は浅く、平底舟でさえ、干潮の前後二時間しか通れない。",
      "指で日付を追った。ハドスンが姿を消したとされる夜。その日の干潮は、午前二時七分。",
      "四日前の午前二時。屋敷の誰も起きていない時刻だ。",
    ],
    addClues: ["tide_table"],
    next: "c2_hub",
  },

  // ── 調査D：沼と舟着き場 ───────────────────
  {
    id: "inv_fen_0",
    chapter: "第二章",
    location: "沼",
    scene: "fen",
    characters: ["holmes"],
    text: [
      "屋敷の裏手から葦の間を抜けると、板を渡しただけの舟着き場がある。",
      "雨は上がりかけていた。水面に灯を近づけると、平底舟が二艘、鎖でつないである。舟底には雨水が溜まり、その中で枯れた葦が回っていた。",
      "四日前の夜、ここで何かがあった。そう考える理由はまだない。ただ、この場所だけが、屋敷から人目につかずに出られる唯一の道だった。",
    ],
    audio: [
      { kind: "bgm", asset: "quiet_fen", volume: 0.35 },
      { kind: "se", asset: "fen_water", volume: 0.45 },
    ],
    next: "inv_fen_1",
  },
  {
    id: "inv_fen_1",
    chapter: "第二章",
    location: "舟着き場",
    speaker: "ホームズ",
    scene: "fen",
    characters: ["holmes"],
    text: [
      "板の隙間に、灯を近づけた。",
      "この土地の泥は黒い。泥炭と、腐った葦でできた、指で潰すと繊維の残る黒い泥だ。",
      "だが板の隙間に乾いてこびりついていたのは、赤みの強い、きめの細かい粘土だった。爪で削って掌に載せる。この土は、白亜の丘のある土地のものだ。南の──ハンプシャーあたりの。",
      "ここへ来た誰かの靴が、それを運んできた。",
    ],
    addClues: ["red_clay"],
    next: "inv_fen_2",
  },
  {
    id: "inv_fen_2",
    chapter: "第二章",
    location: "舟番小屋",
    scene: "fen",
    characters: ["holmes"],
    text: [
      "舟着き場の脇に、舟番の老人が寝起きする小屋がある。老人は耳が遠く、雨の夜は何も聞こえないと言った。",
      "だが帳面はつけていた。舟を出した者の名前と時刻を、四十年間、一日も欠かさず。",
      "四日前の頁だけ、鉛筆の線が二本引かれ、名前が書かれていない。",
      "「名を言わずに持ってったんだ。朝には返っとったがね」老人は言った。「舳先の泥が、乾きかけとった。あれは夜中に出て、明け方に戻った舟だ」",
    ],
    addClues: ["boat_log"],
    audio: [{ kind: "se", asset: "oar", volume: 0.4, pan: 0.3 }],
    next: "c2_hub",
  },
];
