import type { StoryNode } from "../types";

/**
 * 第三章「グローリア・スコット号」
 *
 * 老トレヴァーの死と手記の回想（共通ルート）。
 * 章の終わりで同行者を3ルートから選ぶ。
 */
export const chapter3Nodes: StoryNode[] = [
  {
    id: "c3_0",
    chapter: "第三章",
    location: "二階の寝室",
    scene: "hall",
    characters: ["victor", "fordham"],
    text: [
      "午前四時をまわった頃、二階から人の動く音がした。",
      "階段を上がると、フォーダム医師が寝台の脇に立って、懐中時計を閉じるところだった。",
      "「四時十八分です」",
      "ヴィクターは父の手を握ったまま、何も言わなかった。窓の外はまだ暗く、雨だけが止んでいた。",
    ],
    setFlags: { sawDeath: true },
    audio: [
      { kind: "stop", fadeMs: 800 },
      { kind: "silence", durationMs: 2500 },
      { kind: "se", asset: "clock", volume: 0.3 },
    ],
    next: "c3_1",
  },
  {
    id: "c3_1",
    chapter: "第三章",
    location: "書斎",
    speaker: "ヴィクター",
    scene: "study",
    characters: ["victor", "holmes"],
    text: [
      "夜が明けきる前に、ヴィクターは書斎の壁の金庫を開けた。鍵の在処は、父が去年のうちに教えてあったという。",
      "中には土地の権利書と、母の写真と、それから厚い封筒が一つ入っていた。",
      "表書きは父の字で、一行だけ。",
      "『わが子ヴィクターへ。わたしが死んだ日に読め』",
    ],
    addClues: ["trevor_memoir"],
    audio: [{ kind: "se", asset: "paper", volume: 0.5 }],
    next: "c3_2",
  },
  {
    id: "c3_2",
    chapter: "第三章",
    location: "書斎",
    speaker: "ヴィクター",
    scene: "study",
    characters: ["victor"],
    text: [
      "「読んでくれ」ヴィクターは封筒をわたしに押しつけた。「ぼくは……手が」",
      "見ると、彼の指は封を切れないほど震えていた。",
      "わたしは灯を近づけ、最初の一行を読んだ。そして、その一行で、この家の三十年が説明されてしまった。",
    ],
    next: "c3_3",
  },
  {
    id: "c3_3",
    chapter: "第三章",
    location: "手記",
    speaker: "手記",
    scene: "ship",
    text: [
      "『わたしの名はトレヴァーではない。ジェイムズ・アーミテージという』",
      "『一八五五年、わたしはロンドンの銀行の行員だった。二十三歳で、賭けごとの借金があり、金庫の金に手をつけた。三日で返すつもりだった。三日目に露見した』",
      "『判決は流刑。オーストラリア行きの囚人輸送船グローリア・スコット号に、わたしは三十七人の囚人とともに積み込まれた』",
    ],
    audio: [
      { kind: "bgm", asset: "memoir", volume: 0.35, fadeMs: 2000 },
      { kind: "se", asset: "rope", volume: 0.3, pan: -0.3 },
    ],
    next: "c3_4",
  },
  {
    id: "c3_4",
    chapter: "第三章",
    location: "手記",
    speaker: "手記",
    scene: "ship",
    characters: ["prendergast"],
    text: [
      "『船には囚人が三十八名、水夫が二十六名、監視の兵が十八名。ほかに船長、三人の航海士、医者、牧師、看守が四人。合わせて九十人あまりが、あの狭い木の箱に詰め込まれていた』",
      "『囚人の中に、ジャック・プレンダーガストという男がいた』",
      "『新聞で名を知らぬ者はなかった。ロンドン中の紳士から二十五万ポンドを騙し取った詐欺師だ。背が高く、物腰は貴族のようで、鎖につながれていてさえ、看守のほうが彼に敬語を使った』",
    ],
    next: "c3_5",
  },
  {
    id: "c3_5",
    chapter: "第三章",
    location: "手記",
    speaker: "手記",
    scene: "ship",
    characters: ["prendergast"],
    text: [
      "『航海に出て三週目、プレンダーガストはわたしに囁いた。この船はわたしのものだ、と』",
      "『事実そうだった。船つきの牧師はウィルスンという彼の仲間で、聖書の箱の底には拳銃が入っていた。看守のうち二人、二等航海士、そして船医までが、彼の金で買われていた』",
      "『彼は騙し取った金を、最後の一ペニーまで、この船を買うために使ったのだ』",
    ],
    audio: [{ kind: "se", asset: "rope", volume: 0.35, pan: 0.3 }],
    next: "c3_6",
  },
  {
    id: "c3_6",
    chapter: "第三章",
    location: "手記",
    speaker: "手記",
    scene: "ship",
    text: [
      "『決行の夜のことは、なるべく短く書く』",
      "『船倉の鎖が外された。武器が配られた。船長は自室で撃たれ、甲板に出てきた兵たちは階段の下で待ち伏せに遭った。二十分で終わった』",
      "『そのあとが、わたしの一生を決めた』",
      "『生き残った者たちを、プレンダーガストは一人ずつ海へ落とすと言った。エヴァンズという若い囚人が、それは殺人だと言って立ちはだかった。わたしも隣に立った』",
    ],
    audio: [
      { kind: "bgm", asset: "confront", volume: 0.4, fadeMs: 1500 },
      { kind: "se", asset: "heartbeat", volume: 0.35 },
    ],
    next: "c3_7",
  },
  {
    id: "c3_7",
    chapter: "第三章",
    location: "手記",
    speaker: "手記",
    scene: "ship",
    text: [
      "『わたしたちは撃たれてもおかしくなかった。だがプレンダーガストは、気まぐれに笑って言った。──では、おまえたちにはボートをやろう』",
      "『エヴァンズとわたし、それに助命された何人かが、小舟に乗せられて海へ降ろされた。食糧と、水と、羅針盤が一つ。それだけだ』",
      "『漕ぎ離れて一時間ほどたった頃、うしろで光った』",
    ],
    next: "c3_8",
  },
  {
    id: "c3_8",
    chapter: "第三章",
    location: "手記",
    speaker: "手記",
    scene: "ship",
    text: [
      "『音は、光よりずっと遅れて届いた』",
      "『振り返ったときには、水平線の上に黒い雲が立ち上がっていた。火薬庫がやられたのだ。マストも、甲板も、あの九十人が争っていたものが全部、一度に空へ上がった』",
      "『わたしたちは何時間も、そこに何かが浮いていないかと目を凝らしていた。何も浮かんでいなかった』",
    ],
    audio: [
      { kind: "stop", fadeMs: 300 },
      { kind: "silence", durationMs: 3000 },
      { kind: "se", asset: "explosion", volume: 0.55 },
    ],
    next: "c3_9",
  },
  {
    id: "c3_9",
    chapter: "第三章",
    location: "手記",
    speaker: "手記",
    scene: "ship",
    text: [
      "『翌日、わたしたちはオーストラリア行きの帆船ホットスパー号に拾われた。船長は、わたしたちを難破した客船の生き残りだと信じた』",
      "『エヴァンズとわたしは、金鉱で当てた。彼はビードウズと名を変え、わたしはトレヴァーと名を変えて、それぞれイングランドの別の土地へ帰った。二十年、わたしたちは幸福だった』",
      "『そして今年、ハドスンが来た』",
    ],
    audio: [{ kind: "bgm", asset: "memoir", volume: 0.3 }],
    next: "c3_10",
  },
  {
    id: "c3_10",
    chapter: "第三章",
    location: "手記",
    speaker: "手記",
    scene: "ship",
    characters: ["hudson"],
    text: [
      "『あの男は水夫だった。あの夜、甲板にいた。そして爆発を生き延びた、ただ一人の人間だ』",
      "『わたしは彼に、望むだけのものを与えた。金も、家も、酒も。それでも足りなかった』",
      "『先週、彼はこう言った。──もう一度あれをやろうじゃないか、旦那』",
      "『ヴィクター。父は臆病者だった。おまえの父は、人が殺されるのを見て、ボートに乗った男だ』",
    ],
    next: "c3_11",
  },
  {
    id: "c3_11",
    chapter: "第三章",
    location: "書斎",
    speaker: "ヴィクター",
    scene: "study",
    characters: ["victor", "holmes"],
    text: [
      "手記はそこで終わっていた。最後の頁の下三分の一は白いままだ。",
      "ヴィクターは長いこと、窓の外の白みかけた空を見ていた。",
      "「ぼくの家は、人殺しの金で建ってるのか」",
      "「違う」わたしは言った。「きみのお父上は、殺すのを拒んで小舟に乗った。それだけは、はっきり書いてある」",
    ],
    audio: [{ kind: "stop", fadeMs: 2000 }],
    next: "c3_12",
  },
  {
    id: "c3_12",
    chapter: "第三章",
    location: "書斎",
    speaker: "ホームズ",
    scene: "study",
    characters: ["holmes"],
    text: [
      "だが、手記は一つのことを説明していなかった。",
      "ハドスンは四日前に、この家を出た。ハンプシャーへ行くと言い残して。そして翌日、ハンプシャーから届いた手紙が、老人を殺した。",
      "その手紙は、老人に「逃げろ」と言っているように思われてならない。だとすれば、書いたのはハドスンではない。",
      "書いたのは、三十年前にもう一艘のボートに乗っていた男だ。",
    ],
    audio: [{ kind: "bgm", asset: "unease", volume: 0.35 }],
    next: "c3_13",
  },
  {
    id: "c3_13",
    chapter: "第三章",
    location: "書斎",
    speaker: "ホームズ",
    scene: "study",
    characters: ["holmes"],
    text: [
      "今夜のうちに、確かめなければならないことがある。だが一人でやれることには限りがあった。",
      "誰と動くか。それは、誰に何を話すかということでもある。",
    ],
    choices: [
      {
        label: "ヴィクターに、疑っていることを全部話す",
        next: "route_v_0",
        setCompanion: "victor",
        setFlags: { trustVictor: true },
        addClues: ["victor_testimony"],
        note: "系統3（偽装）が成立する",
      },
      {
        label: "フォーダム医師を訪ね、十七年ぶんの記憶を借りる",
        next: "route_f_0",
        setCompanion: "fordham",
        setFlags: { withFordham: true },
        addClues: ["fordham_note", "hired_gig"],
        note: "系統1（過去）と系統2（今夜の移動）が成立する",
      },
      {
        label: "誰にも言わず、夜の沼を見張る",
        next: "route_a_0",
        setCompanion: "alone",
        setFlags: { alone: true },
        addClues: ["night_watch"],
        note: "系統3（偽装）が成立する",
      },
    ],
  },

  // ── 同行者ルートV：ヴィクター ─────────────
  {
    id: "route_v_0",
    chapter: "第三章",
    location: "書斎",
    speaker: "ホームズ",
    scene: "study",
    characters: ["holmes", "victor"],
    text: [
      "「ヴィクター。座ってくれ。きみに隠したまま動くのは、たぶん間違いだ」",
      "わたしは全部話した。ハドスンの荷物のこと。手紙の消印。三十年前の新聞に載っているはずの名前。そして、この家の裏の沼から、人目につかずに水路へ出られること。",
      "彼は途中で一度も口を挟まなかった。話し終えると、両手で顔をこすった。",
    ],
    audio: [{ kind: "bgm", asset: "unease", volume: 0.3 }],
    next: "route_v_1",
  },
  {
    id: "route_v_1",
    chapter: "第三章",
    location: "書斎",
    speaker: "ヴィクター",
    scene: "study",
    characters: ["victor"],
    text: [
      "「……ホームズ。ぼくは、一つ黙ってたことがある」",
      "「五日前の夜だ。親父とハドスンが言い争ってた。ぼくは廊下で聞いてた」",
      "「金の話だと思ったんだ。いつもそうだったから。でも違った」",
    ],
    next: "route_v_2",
  },
  {
    id: "route_v_2",
    chapter: "第三章",
    location: "回想・廊下",
    speaker: "ヴィクター",
    scene: "hall",
    characters: ["hudson", "trevor"],
    text: [
      "「ハドスンはこう言った。『もう一度あれをやろうじゃないか、旦那。あんたとあの男の分け前で、今度は三人でやる』」",
      "「親父は答えた。『やめろ。今度こそ人が死ぬ』」",
      "「ハドスンは笑って言ったんだ。『前のときも死んだよ』」",
    ],
    addClues: [],
    audio: [{ kind: "se", asset: "heartbeat", volume: 0.4 }],
    next: "route_v_3",
  },
  {
    id: "route_v_3",
    chapter: "第三章",
    location: "書斎",
    speaker: "ホームズ",
    scene: "study",
    characters: ["holmes", "victor"],
    text: [
      "「ヴィクター、それは決定的だ」",
      "ハドスンは金を無心しに来たのではなかった。彼はこの二人に、もう一度何かを「やらせる」ために来たのだ。",
      "そして──二人のうち一人は、それを断らなかった可能性がある。断らなかったふりをして、招いた可能性が。",
      "「もし本当にハドスンが自分の足でハンプシャーへ向かったのなら、彼は招かれたんだ。断られたからじゃない」",
    ],
    audio: [{ kind: "bgm", asset: "confront", volume: 0.35 }],
    next: "c4_0",
  },

  // ── 同行者ルートF：フォーダム医師 ─────────
  {
    id: "route_f_0",
    chapter: "第三章",
    location: "村・医師の家",
    speaker: "ホームズ",
    scene: "village",
    characters: ["holmes", "fordham"],
    text: [
      "夜明けの村を歩いて、フォーダム医師の家の戸を叩いた。",
      "医師はまだ外套も脱いでいなかった。白い手袋を外しながら、彼はわたしを診察室へ通した。",
      "「学生さんが、こんな時間に」",
      "「先生は、トレヴァー氏を十七年診てこられた。その前の記録は残っていますか」",
    ],
    audio: [{ kind: "bgm", asset: "unease", volume: 0.3 }],
    next: "route_f_1",
  },
  {
    id: "route_f_1",
    chapter: "第三章",
    location: "診察室",
    speaker: "フォーダム医師",
    scene: "village",
    characters: ["fordham"],
    text: [
      "医師はしばらく黙っていた。それから、書棚のいちばん下から革表紙の帳面を引き出した。",
      "「父の代の診療録です。わたしは、こういうものを捨てられん質でしてな」",
      "一八五七年の頁。この土地に来たばかりの「トレヴァー氏」の初診の記録。",
      "『右肘内側に薬品による瘢痕あり。両手掌に重度の胼胝。索を長く握りし者の手なり。当人、鉱夫と称す』",
    ],
    addClues: [],
    audio: [{ kind: "se", asset: "paper", volume: 0.5 }],
    next: "route_f_2",
  },
  {
    id: "route_f_2",
    chapter: "第三章",
    location: "診察室",
    speaker: "ホームズ",
    scene: "village",
    characters: ["holmes", "fordham"],
    text: [
      "「先生。鉱夫の手と、水夫の手は違いますね」",
      "「違います」医師は静かに言った。「わたしの父も、そう思ったから書いたんでしょう。そして、それきり何も書かなかった」",
      "この土地は、聞かないことで人を受け入れてきた。三十年間、誰も老人に何も聞かなかった。それがこの村の優しさで、同時にこの事件の温床だった。",
    ],
    next: "route_f_3",
  },
  {
    id: "route_f_3",
    chapter: "第三章",
    location: "診察室",
    speaker: "フォーダム医師",
    scene: "village",
    characters: ["fordham"],
    text: [
      "帰りぎわ、医師はふと思い出したように言った。",
      "「そういえば……四日前の晩、妙なものを見ましたよ」",
      "「往診の帰りでしてな。午前一時をまわっていた。県道で、二頭立ての貸馬車とすれ違った。御者は村の者じゃない。幌の中の紳士は、こう、襟で顔を隠しておって」",
      "「この時期にこの道を、真夜中に走る馬車なんぞありません。おまけに馬の脚に、赤い土が跳ねとった。この辺の泥は黒いのに」",
    ],
    addClues: [],
    audio: [{ kind: "bgm", asset: "confront", volume: 0.35 }],
    next: "c4_0",
  },

  // ── 同行者ルートS：単独 ───────────────────
  {
    id: "route_a_0",
    chapter: "第三章",
    location: "沼",
    speaker: "ホームズ",
    scene: "fen",
    characters: ["holmes"],
    text: [
      "誰にも言わなかった。",
      "ヴィクターには父の死の始末がある。医師は口の堅さで信用を得てきた男で、口の堅さは必ずしも味方の性質ではない。",
      "わたしは外套の襟を立て、葦の原へ入った。",
      "潮見表が正しければ、水路が通れるのは午前二時前後の二時間だけだ。",
    ],
    audio: [
      { kind: "bgm", asset: "quiet_fen", volume: 0.3 },
      { kind: "se", asset: "fen_water", volume: 0.45 },
    ],
    next: "route_a_1",
  },
  {
    id: "route_a_1",
    chapter: "第三章",
    location: "葦の原",
    scene: "fen",
    characters: ["holmes"],
    text: [
      "三時間、わたしは同じ姿勢で伏せていた。",
      "冷えは足の指から膝へ、膝から腰へと上がってくる。葦が擦れる音と、遠くで鴨が羽ばたく音のほかには、何もない。",
      "そのあいだに、わたしは考えを一つずつ潰していった。ハドスンが自分で出ていったという説を、四つの理由で潰した。荷物。金。潮の時刻。そして、帳面に書かれなかった舟。",
    ],
    audio: [{ kind: "silence", durationMs: 2200 }],
    next: "route_a_2",
  },
  {
    id: "route_a_2",
    chapter: "第三章",
    location: "葦の原",
    scene: "fen",
    characters: ["holmes"],
    text: [
      "午前二時のすこし前。水路のほうから、櫂の音がした。",
      "規則正しい、慣れた漕ぎ方だった。舟は一艘。漕いでいるのは一人。",
      "わたしは息を殺して、舟が葦の陰を通り過ぎるのを待った。",
    ],
    audio: [{ kind: "se", asset: "oar", volume: 0.5, pan: -0.5 }],
    next: "route_a_3",
  },
  {
    id: "route_a_3",
    chapter: "第三章",
    location: "葦の原",
    speaker: "ホームズ",
    scene: "fen",
    characters: ["holmes"],
    text: [
      "四十分後、同じ舟が戻ってきた。同じ漕ぎ手だ。",
      "だが、舟の様子が違っていた。行きは舷側が水に近く、櫂を入れるたびに重たげに沈んだ。帰りは軽く、浅く、水面を滑るように走った。",
      "行きに積んでいたものを、この男は水路のどこかで降ろしている。",
      "四日前の夜も、同じことが起きたのだ。ただし──向きが逆に。",
    ],
    audio: [
      { kind: "se", asset: "oar", volume: 0.4, pan: 0.5 },
      { kind: "bgm", asset: "confront", volume: 0.35 },
    ],
    next: "c4_0",
  },
];
